### ISSUE TITLE
zig build test fail on zig 0.13.0 src/minilib/TimerQueue.zig

### ISSUE THREAD

**Issue by ngocbd** [Cloudef/zig-aio#23]
![image](https://github.com/user-attachments/assets/4401bad6-d823-40e7-81b4-60fbbaaefc95)
Step to re-procedure 
git fetch origin zig-0.13
 zig build test

same error on master branch

**Comment by YiraSan** [comment]
You seems to be running on 0.14.0

**Comment by Cloudef** [comment]
Maybe cache issue? Or using wrong branch?

**Comment by YiraSan** [comment]
This way more simpler, "git fetch" only retrieve data from the branch; but it doesn't change the branch you're on.
```
git checkout zig-0.13
```
A simple checkout could fix your issue...
