### ISSUE TITLE
how to make coro scheduler multi-threaded

### ISSUE THREAD

**Issue by YiraSan** [Cloudef/zig-aio#28]
This is probably a lack of knowledge, I've been making a code, that is simply doing what is happening in ThreadPool tests. Since I want the coro to be multi-threaded.

I've been doing my stuff, and then I realized by doing that:
```zig
fn _func() !void {
    coro.current(); // ALWAYS null
}

pub fn funcTask() !void {
    try threadpool.yieldForCompletition(_null, .{}, .{});
}

_ = try scheduler.spawn(funcTask, .{}, .{});
```

Is it normal that _func never gets the current frame/task ??
_directly calling the func from the scheduler.spawn works normally_

I was expecting from the ThreadPool test to be the idomatic way of doing that, but maybe I've been doing that the wrong way. (this is probably me).

So if I'm doing things wrong: How to make coro scheduling multi-threaded the proper way ?
(The existence of semaphore confirm to me that this should be possible, otherwise running the scheduler on one thread will makes no point to the existence of semaphore)

**Comment by Bob-van** [comment]
Hi i am here to answer that.
To my best knowledge depends on a backed coro.Scheduler decides to use:
  - posix and iocp are at using default the cpu core count as number of threads to spawn, note that this can be changed thru aio.Options
  - io_uring does not need threads on wait from what i understood since it uses ring-buffer

also sizeable part of backend (mainly Frame) runs on Fibers

**Comment by Bob-van** [comment]
For place to get started and get to know how to use the library, wiki is kinda helpful (although i personally found it confusing at start) -> https://cloudef.github.io/zig-aio/

Things that really helped me are the examples, especially the coro ones -> literally there is a /example

In the end i had to do some code digging, and still asked some really stupid questions here looking back at it.
\+ keep in mind there is currently a bug in scheduler (more in https://github.com/Cloudef/zig-aio/issues/22) that can cause some issues so dont be hard on yourself 😉

**Comment by Cloudef** [comment]
You'd have to have scheduler on every thread and do the scheduling / synchronization yourself.

**Comment by YiraSan** [comment]
> You'd have to have scheduler on every thread

Thats is making much sense, so from that assertion, it means that semaphore is working between scheduler ?

**Comment by Cloudef** [comment]
The sync primitives only work within a single scheduler. There is no thread safety at all in coro. coro.ThreadPool is to offload blocking task to a thread which yields the coroutine until the task on a thread is complete.

> Side question: is it safe to spawn a task from outside the scheduler thread ?

No it is not.

I'm still unsure if I add MultiThreadedScheduler or something, that would also need thread safe sync primitives, which kinda defeats the point in the end I think. The IO backends are already using thread pools (apart from io_uring, which you don't want anyway). I think this kind of design won't scale that well anyways.

You'd rather want to think this whole program level and make different threads do different things where they still can have their own schedulers. Note that you can still create a scheduler on coro.ThreadPool task and do coroutiny things there as well, but the threaded task eventually should come up with a result, or the coroutine that spawned the blocking task will yield forever.

**Comment by YiraSan** [comment]
This being said, before posting that comment I thought about your answer, and started rewriting my whole project thinking differently. What about using a same socket between two schedulers ?

I've been making a server using coro and aio, I have one unique networking thread, and multiple regions threads, for each region of a defined world (depending on the connections), there will be maybe a total of 8 threads (depending on the cpu count and the need for threads). Every threads is using its own scheduler.

I need to send packet from outside the networking thread' scheduler, is it a problem ?

Note: I only receive from the networking thread.

**Comment by Cloudef** [comment]
As long as you don't race, using same socket with AIO ops is okay.
