### ISSUE TITLE
Support sendto() for broadcast udp

### ISSUE THREAD

**Issue by mrjbq7** [Cloudef/zig-aio#37]
I'm trying to use SO_BROADCAST with zig-aio, and I can't seem to find a wrapper for ``sendto()``:

https://linux.die.net/man/2/sendto

It exists in ``std.posix``:

https://ziglang.org/documentation/master/std/#std.posix.sendto

**Comment by Cloudef** [comment]
zig-aio only supports io_uring operators, see list here:
https://unixism.net/loti/ref-iouring/io_uring_enter.html

The alternative sendmsg already exists
