### ISSUE TITLE
Support recvfrom() getting a peer/sender address

### ISSUE THREAD

**Issue by mrjbq7** [Cloudef/zig-aio#38]
It would be nice to use ``recvfrom()`` with a UDP socket to fill in a peer address of the sender that set the packet.

**Comment by Cloudef** [comment]
zig-aio mainly targets io_uring supported operations. With io_uring you are supposed to use recvmsg instead of recvfrom.
See list of io_uring operations here: https://unixism.net/loti/ref-iouring/io_uring_enter.html

**Comment by mrjbq7** [comment]
How would I obtain the peer address with recvmsg?On Dec 30, 2024, at 2:15 AM, Jari Vetoniemi ***@***.***> wrote:﻿
zig-aio mainly targets io_uring supported operations. With io_uring you are supposed to use recvmsg instead of recvfrom.
See list of io_uring operations here: https://unixism.net/loti/ref-iouring/io_uring_enter.html

**Comment by mrjbq7** [comment]
Okay, so I would need to provide space in the ``msghdr`` for that:

https://stackoverflow.com/a/42090305/8031
